#!/bin/sh

DBNAME=plruby_test
export DBNAME

#uncomment below if your usual db account is not superuser
#superuser="postgres"

which dropdb createdb psql
if [ $? -ne 0 ]; then
  pg_path=`pg_config --bindir`/
else
  pg_path=""
fi

sleep 1
echo "**** Destroy old database $DBNAME ****"
${pg_path}dropdb $DBNAME

echo "**** Create test database $DBNAME ****"
${pg_path}createdb $DBNAME

echo "**** Create procedural language plruby$2 ****"
"${RUBY-ruby}" ../b.rb $*
if [ x$superuser = x"" ]; then
  ${pg_path}psql -q -n -X $DBNAME < test_mklang.sql
else
  ${pg_path}psql -U $superuser -q -n -X $DBNAME < test_mklang.sql
fi

echo "**** Create tables, functions and triggers ****"
${pg_path}psql -q -n -X $DBNAME < test_setup.sql

echo "**** Running test queries ****"
${pg_path}psql -q -n -X -e $DBNAME < test_queries.sql > test.out 2>&1

if cmp -s test.expected.$1 test.out; then
  echo "    Tests passed O.K."
else
  echo "    Tests failed - look at diffs between"
  echo "    test.expected.$1 and test.out"
fi

